### ISSUE TITLE
ERROR Error loading scripts from npm package - TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by xsunnydong** [ineo6/hubot-dingtalk#8]
hubot@7b6192d48514:~$ ./bin/hubot -a dingtalk
up to date in 0.492s

7 packages are looking for funding
  run `npm fund` for details

[Tue May 24 2022 01:48:44 GMT+0000 (Coordinated Universal Time)] INFO Constructor
[Tue May 24 2022 01:48:44 GMT+0000 (Coordinated Universal Time)] INFO Run
[Tue May 24 2022 01:48:44 GMT+0000 (Coordinated Universal Time)] ERROR Error loading scripts from npm package - TypeError: require(...) is not a function
  at /home/hubot/node_modules/hubot/src/robot.js:409:52
  at Array.forEach (<anonymous>:null:null)
  at Robot.loadExternalScripts (/home/hubot/node_modules/hubot/src/robot.js:409:25)
  at /home/hubot/node_modules/hubot/bin/hubot.js:207:13
  at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
安装方式：npm install 
hubot-dingtalk版本：1.5.0
nodejs版本：v12.22.12
npm版本：6.14.16
hubot版本：3.3.2
大佬好，初学HUBOT 使用此dingtalk适配器报错

**Comment by zhangrr** [comment]
https://bajie.dev/posts/20230301-hubot_dingding/

试试这个教程
